language: python
python:      
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install --no-cache-dir tox
  - pip install --no-cache-dir pycodestyle
# command to run tests
script:
  - tox